apiVersion: v1
kind: ConfigMap
metadata:
  name: otel
data:
  OTEL_ENVIRONMENT: "development"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
  OTEL_EXPORTER_OTLP_INSECURE: "true"
  OTEL_BSP_SCHEDULE_DELAY: "500ms"
