apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-llm
spec:
  selector:
    matchLabels:
      app: ocr-llm
  template:
    metadata:
      labels:
        app: ocr-llm
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: ocr-llm
          image: ${DOCKER_REPO}:${DRONE_COMMIT_SHA}
          args: ["ocr-llm"]
          resources:
            requests:
              cpu: "100m"
              memory: "24Mi"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /config.yaml
              subPath: config.yaml
            - name: prompts
              mountPath: /prompts.yaml
              subPath: prompts.yaml
          envFrom:
            - configMapRef:
                name: otel-config
          env:
            - name: OTEL_SERVICE_NAME
              value: "ocr-llm"
            - name: OTEL_SERVICE_VERSION
              value: "0.0.0"
      volumes:
        - name: config
          configMap:
            name: ocr-config
        - name: prompts
          configMap:
            name: prompts-config

---
apiVersion: v1
kind: Service
metadata:
  name: ocr-llm
spec:
  selector:
    app: ocr-llm
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ocr-llm-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ocr-llm
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 300
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 1000
