apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram
spec:
  selector:
    matchLabels:
      app: telegram
  template:
    metadata:
      labels:
        app: telegram
    spec:
      containers:
        - name: telegram
          image: ${DOCKER_REPO}:${DRONE_COMMIT_SHA}
          args: ["telegram"]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
          envFrom:
            - configMapRef:
                name: otel-config
          env:
            - name: OTEL_SERVICE_NAME
              value: "api"
            - name: OTEL_SERVICE_VERSION
              value: "0.0.0"
      volumes:
        - name: config
          configMap:
            name: telegram-config
---
apiVersion: v1
kind: Service
metadata:
  name: telegram
spec:
  selector:
    app: telegram
  ports:
    - port: 80
      targetPort: 8080
