apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram
spec:
  selector:
    matchLabels:
      app: telegram
  template:
    metadata:
      labels:
        app: telegram
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: telegram
          image: ${DOCKER_REPO}:${DRONE_COMMIT_SHA}
          args: ["telegram"]
          resources:
            requests:
              cpu: "100m"
              memory: "24Mi"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /config.yaml
              subPath: config.yaml
          envFrom:
            - configMapRef:
                name: otel-config
          env:
            - name: OTEL_SERVICE_NAME
              value: "api"
            - name: OTEL_SERVICE_VERSION
              value: "0.0.0"
      volumes:
        - name: config
          configMap:
            name: ocr-config
---
apiVersion: v1
kind: Service
metadata:
  name: telegram
spec:
  selector:
    app: telegram
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: telegram-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: telegram
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
